name: Deploy

on:
    push:
        branches:
            - develop/main
            - main
        paths-ignore:
            - "**/*.md"
            - "**/README.*"
env:
    VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
    VITE_IMAGE_SERVICE_URL: ${{secrets.VITE_IMAGE_SERVICE_URL}}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '22.12.0'
                
            - name: Install npm
              run: npm i -g npm@11.0.0

            - name: Install dependencies
              run: npm i

            - name: Build project
              run: npm run build

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v4
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/develop/main' || github.ref=='refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
